import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import express from 'express';
import request from 'supertest';
import {pool} from '../src/db/pool.js';
import {clientPool} from '../src/db/clientPool.js';
import {getVeiculosPool} from '../src/db/pool-veiculos.js';
import {config, quoteIdent} from '../src/config.js';
import {manutencaoPlantaoRouter} from '../src/routes/manutencaoPlantao.js';
import {requireRoutePermission} from '../src/middleware/permissions.js';
import {enforceReadOnly} from '../src/middleware/readOnly.js';

test('controle de custos: concorrência, autoria, edição, exclusão, auditoria e conferência', {skip:process.env.PLANTAO_DB_TEST !== '1'}, async t=>{
  const original = config.db.schema;
  const schema = `plantao_test_${Date.now()}`;
  const driver = {id:42,login:'motorista',permissions:{'manutencao-plantao':true}};
  const reviewer = {id:43,login:'financeiro',permissions:{'conferencia-manutencao':true}};
  const makeApp = user => {
    const app=express();app.use(express.json());app.use((req,_res,next)=>{req.user=user;next();});
    app.use(requireRoutePermission);app.use(enforceReadOnly);app.use(manutencaoPlantaoRouter);
    app.use((error,_req,res,_next)=>res.status(500).json({error:error.message}));return app;
  };
  const driverApp=makeApp(driver), reviewerApp=makeApp(reviewer);
  const body={plate:'ABC1234',amount:200,service:'Borracharia',supplier:'Oficina Teste',expenseDate:'2026-09-30',document:'NF-123'};
  const path='/manutencao-plantao/lancamentos';
  try {
    await pool.query(`CREATE SCHEMA ${quoteIdent(schema)}`);
    const client=await pool.connect();
    try {
      await client.query('BEGIN');
      await client.query(`SET LOCAL search_path TO ${quoteIdent(schema)}`);
      const baseline=await fs.readFile(new URL('../sql/048_permissoes_telas_plantao.sql',import.meta.url),'utf8');
      await client.query(baseline.slice(baseline.indexOf('CREATE TABLE IF NOT EXISTS manutencao_plantao')));
      await client.query("INSERT INTO manutencao_plantao (id,placa,valor,servico,usuario_id,usuario_login,criado_em) VALUES ('55926d25-6e7d-4c22-a36d-747c0402c18a','DEF4G56',15,'Outros',42,'motorista','2026-10-01T01:00:00Z')");
      const migration=await fs.readFile(new URL('../sql/050_plantao_controle_custos.sql',import.meta.url),'utf8');
      await client.query(migration);await client.query(migration);
      await client.query(await fs.readFile(new URL('../sql/054_plantao_pago_lancado.sql',import.meta.url),'utf8'));
      await client.query(await fs.readFile(new URL('../sql/055_plantao_data_pagamento.sql',import.meta.url),'utf8'));
      await client.query(await fs.readFile(new URL('../sql/056_plantao_despesas_motorista.sql',import.meta.url),'utf8'));
      await client.query(await fs.readFile(new URL('../sql/057_plantao_fotos_ocr.sql',import.meta.url),'utf8'));
      await client.query(await fs.readFile(new URL('../sql/058_plantao_arla.sql',import.meta.url),'utf8'));
      assert.equal((await client.query('SELECT data_despesa::text AS dia FROM manutencao_plantao')).rows[0].dia,'2026-09-30');
      await client.query('COMMIT');
    } catch(error) {await client.query('ROLLBACK');throw error;} finally {client.release();}
    config.db.schema=schema;
    t.mock.method(getVeiculosPool(),'query',async sql=>({rows:sql.includes('SELECT m.municipio') ? [{municipio:'Criciúma',uf:'SC',rodovia:'BR-101',rua:null,data_hora:new Date().toISOString()}] : sql.includes('mensagens_cb') ? [{placa:'ABC1234',odometro:197611.7,data_hora:new Date().toISOString()}] : [{placa:'ABC1234'},{placa:'DEF4G56'}]}));
    t.mock.method(clientPool,'query',async()=>({rows:[]}));
    const km=await request(driverApp).get('/manutencao-plantao/placas/ABC1234/hodometro');
    assert.equal(km.status,200);assert.equal(km.body.odometer,197611.7);assert.equal(km.body.source,'telemetria');
    assert.equal((await request(reviewerApp).get('/manutencao-plantao/placas/ABC1234/hodometro')).status,200);
    assert.equal((await request(driverApp).get('/manutencao-plantao/placas/ZZZ9999/hodometro')).status,404);
    const position=await request(driverApp).get('/manutencao-plantao/placas/ABC1234/localizacao');
    assert.equal(position.status,200);assert.equal(position.body.location,'Criciúma / SC — BR-101');assert.equal(position.body.source,'telemetria');
    assert.equal((await request(reviewerApp).get('/manutencao-plantao/placas/ABC1234/localizacao')).status,200);
    assert.equal((await request(driverApp).get('/manutencao-plantao/placas/ZZZ9999/localizacao')).status,404);
    const parallel=await Promise.all([request(driverApp).post(path).send(body),request(driverApp).post(path).send(body)]);
    assert.deepEqual(parallel.map(r=>r.status).sort(),[201,409]);
    let record=parallel.find(r=>r.status===201).body.record;
    assert.equal(record.authorId,42);assert.equal(record.expenseDate,'2026-09-30');assert.equal(record.version,1);
    const id=record.id;
    assert.equal((await request(driverApp).post(path).send({...body,paid:true})).status,403);
    assert.equal((await request(driverApp).put(`${path}/${id}`).send({...body,version:1,posted:true})).status,403);
    assert.equal((await request(driverApp).patch(`/manutencao-plantao/conferencia/${id}/controle`).send({version:1,paid:true})).status,403);
    assert.equal((await request(driverApp).post(path).send({...body,plate:'DEF4G56',amount:250,expenseDate:'2026-09-29',document:'nf 123'})).status,409);
    assert.equal((await request(makeApp({...driver,id:99})).put(`${path}/${id}`).send({...body,version:1})).status,403);
    assert.equal((await request(makeApp({...driver,id:99})).delete(`${path}/${id}`).send({version:1,reason:'duplicado'})).status,403);
    assert.equal((await request(makeApp({...driver,id:99})).get(`${path}/${id}/historico`)).status,403);
    let response=await request(reviewerApp).put(`/manutencao-plantao/conferencia/${id}`).send({...body,amount:220,version:1});
    assert.equal(response.status,200,JSON.stringify(response.body));record=response.body.record;
    assert.equal(record.authorId,42);assert.equal(record.version,2);assert.equal(record.amount,220);
    assert.equal((await request(driverApp).put(`${path}/${id}`).send({...body,version:1})).status,409);
    assert.equal((await request(reviewerApp).patch(`/manutencao-plantao/conferencia/${id}`).send({version:1})).status,409);
    response=await request(driverApp).get(`${path}/${id}/historico`);
    assert.equal(response.body.history.length,2);assert.equal(Number(response.body.history[0].antes.valor),200);assert.equal(Number(response.body.history[0].depois.valor),220);assert.equal(response.body.history[0].usuario_login,'financeiro');
    response=await request(reviewerApp).patch(`/manutencao-plantao/conferencia/${id}`).send({version:2});
    assert.equal(response.status,200);assert.equal(response.body.record.checkedBy,'financeiro');
    assert.equal((await request(driverApp).put(`${path}/${id}`).send({...body,version:3})).status,409);
    assert.equal((await request(driverApp).delete(`${path}/${id}`).send({version:3,reason:'duplicado'})).status,409);
    response=await request(reviewerApp).patch(`/manutencao-plantao/conferencia/${id}/controle`).send({version:3,paymentDate:"2026-09-30",posted:false});
    assert.equal(response.status,200);assert.equal(response.body.record.paid,true);assert.equal(response.body.record.paymentDate,"2026-09-30");assert.equal(response.body.record.posted,false);assert.equal(response.body.record.checked,true);
    assert.equal((await request(driverApp).patch(`${path}/${id}/controle`).send({version:3,posted:true})).status,403);
    assert.equal((await request(makeApp({...driver,id:99})).patch(`${path}/${id}/controle`).send({version:4,posted:true})).status,403);
    response=await request(driverApp).get(`${path}/${id}/historico`);
    assert.equal(response.body.history[0].evento,'status');assert.equal(response.body.history[0].depois.pago,true);
    assert.equal((await request(reviewerApp).patch(`/manutencao-plantao/conferencia/${id}/controle`).send({version:4,paymentDate:"2099-01-01"})).status,400);
    assert.equal((await request(reviewerApp).patch(`/manutencao-plantao/conferencia/${id}/controle`).send({version:4,paymentDate:"2026-02-30"})).status,400);
    assert.equal((await request(driverApp).patch(`${path}/${id}/controle`).send({version:4,paymentDate:"2026-09-30"})).status,403);
    response=await request(reviewerApp).patch(`/manutencao-plantao/conferencia/${id}/controle`).send({version:4,posted:true});
    assert.equal(response.body.record.paymentDate,"2026-09-30");assert.equal(response.body.record.paid,true);
    response=await request(reviewerApp).patch(`/manutencao-plantao/conferencia/${id}/controle`).send({version:5,paymentDate:null});
    assert.equal(response.status,200);assert.equal(response.body.record.paid,false);assert.equal(response.body.record.paymentDate,null);assert.equal(response.body.record.posted,true);
    response=await request(driverApp).post(path).send({...body,document:'NF-456',amount:100});
    assert.equal(response.status,201);const removed=response.body.record.id;
    assert.equal((await request(driverApp).delete(`${path}/${removed}`).send({version:1,reason:'Lançado por engano'})).status,200);
    response=await request(driverApp).get(path);assert.ok(!response.body.records.some(r=>r.id===removed));
    response=await request(driverApp).get(`${path}/${removed}/historico`);assert.equal(response.body.history[0].evento,'delete');assert.equal(response.body.history[0].depois.motivo_exclusao,'Lançado por engano');
    assert.equal((await request(driverApp).post(path).send({...body,document:'NF-456',amount:100})).status,201);
    const fuel={...body,source:'motorista',service:'Abastecimento',amount:1200,document:'POSTO-123',liters:200.5,odometer:125430,location:'Criciúma',receipt:'data:image/png;base64,iVBORw0KGgo='};
    assert.equal((await request(driverApp).post(path).send({...fuel,liters:null})).status,400);
    assert.equal((await request(driverApp).post(path).send({...fuel,odometer:null})).status,400);
    assert.equal((await request(driverApp).post(path).send({...fuel,receipt:'data:image/svg+xml;base64,PHN2Zz4='})).status,400);
    response=await request(driverApp).post(path).send(fuel);
    assert.equal(response.status,201,JSON.stringify(response.body));const fuelId=response.body.record.id;
    assert.equal(response.body.record.source,'motorista');assert.equal(response.body.record.liters,200.5);assert.equal(response.body.record.hasReceipt,true);
    assert.equal((await request(driverApp).get(`${path}/${fuelId}/comprovante`)).body.receipt,fuel.receipt);
    assert.equal((await request(makeApp({...driver,id:99})).get(`${path}/${fuelId}/comprovante`)).status,403);
    assert.equal((await request(reviewerApp).get(`/manutencao-plantao/conferencia/${fuelId}/comprovante`)).body.receipt,fuel.receipt);
    response=await request(reviewerApp).put(`/manutencao-plantao/conferencia/${fuelId}`).send({...fuel,receipt:undefined,amount:1300,version:1});
    assert.equal(response.status,200);assert.equal(response.body.record.hasReceipt,true);assert.equal(response.body.record.liters,200.5);
    assert.equal((await request(driverApp).get(`${path}/${fuelId}/historico`)).body.history[0].depois.comprovante_foto,true);
    response=await request(driverApp).get(path);assert.ok(response.body.records.some(r=>r.id===fuelId));assert.ok(!response.body.records.some(r=>r.receipt));
    assert.equal((await request(driverApp).post(path).send({...body,source:'motorista',service:'Outros',note:''})).status,400);
    assert.equal((await request(driverApp).post(path).send({...body,source:'motorista',service:'Manutenção',amount:99,document:'SEM-FOTO'})).status,201);
    const photo='data:image/png;base64,iVBORw0KGgo=';
    response=await request(driverApp).post(path).send({...fuel,document:'FOTOS-3',amount:3966.83,arlaLiters:41.5,arlaAmount:157.28,fuelAmount:3809.55,odometer:197611.7,photos:{odometer:photo,pump:photo,invoice:photo}});
    assert.equal(response.status,201,JSON.stringify(response.body));const photosId=response.body.record.id;
    assert.equal(response.body.record.arlaLiters,41.5);assert.equal(response.body.record.arlaAmount,157.28);assert.equal(response.body.record.odometer,197611.7);assert.equal(response.body.record.fuelAmount,3809.55);
    assert.deepEqual(response.body.record.photoKinds,{odometer:true,pump:true,invoice:true});
    response=await request(driverApp).get(`${path}/${photosId}/comprovante`);assert.deepEqual(response.body.photos,{odometer:photo,pump:photo,invoice:photo});
    response=await request(driverApp).put(`${path}/${photosId}`).send({...fuel,document:'FOTOS-3',amount:3966.83,odometer:197611.7,version:1,photos:{pump:null}});
    assert.equal(response.status,200);assert.deepEqual(response.body.record.photoKinds,{odometer:true,pump:false,invoice:true});assert.equal(response.body.record.fuelAmount,3809.55);
    response=await request(driverApp).get(`${path}/${photosId}/historico`);assert.equal(response.body.history[0].depois.painel_foto,true);
    assert.equal((await request(makeApp({...driver,id:99})).get(`${path}/${photosId}/comprovante`)).status,403);
    assert.equal((await request(driverApp).post(path).send({...fuel,document:'ARLA-INCOMPLETO',arlaLiters:20})).status,400);
    assert.equal((await request(driverApp).post(path).send({...fuel,document:'ARLA-SOMA',fuelAmount:1100,arlaLiters:20,arlaAmount:200})).status,400);
    assert.equal((await request(driverApp).post(path).send({...fuel,document:"VALOR-INVALIDO",amount:1234,fuelAmount:2000})).status,400);
  } finally {
    config.db.schema=original;
    await pool.query(`DROP SCHEMA IF EXISTS ${quoteIdent(schema)} CASCADE`);
    await pool.end();await clientPool.end();await getVeiculosPool().end();
  }
});
