ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS perm_folgas_motoristas BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS perm_trafegus BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS perm_oportunidades_retorno BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS perm_consulta_nfe BOOLEAN NOT NULL DEFAULT TRUE;
